component RadioButton {
    in property <string> label;

    min-height: 24px;

    Rectangle {
        width: 100%;
        height: 100%;

        background: #ff000055;
    }

    FlexboxLayout {
        // flex-wrap: no-wrap;
        cross-axis-alignment: center;
        spacing: 8px;

        Rectangle {
            width: 24px;
            height: 24px;
            border-width: 3px;
            border-color: #19a7d8;
            border-radius: 12px;
        }

        Text {
            text: root.label;
            color: white;
            font-size: 18px;
            vertical-alignment: center;
        }
    }
}


export component TestCase inherits Window {
    width: 700px;
    height: 420px;
    background: #071b24;

    Rectangle {
        x: 30px;
        y: 30px;
        width: parent.width - 60px;
        height: parent.height - 60px;
        background: #062d3b;
        border-radius: 8px;

        // FlexboxLayout {
        //     width: 100%;
        //     flex-direction: column;
        //     padding: 48px;
        //     spacing: 16px;
        //     alignment: center;
        //     cross-axis-alignment: start;

        //     RadioButton { label: "English (US)"; }
        //     RadioButton { label: "English (British)"; }
        //     RadioButton { label: "Deutsch"; }
        //     RadioButton { label: "Français"; }
        // }
        RadioButton { label: "English (US)"; }
    }
}
